name: Hackathon-Eval
on: [push,pull_request]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          git fetch --prune
          cd scripts/
          python main.py --eval
          cml-publish score.png --md >> report3.md
          cml-send-comment report.md
          cml-send-comment report2.md